### ISSUE TITLE
Align data format for trusted domains in request.rs with the format used in server.rs

### ISSUE THREAD

**Issue by sophie-cluml** [petabi/review-protocol#39]
In server.rs, trusted domains are being sent without being wrapped in a Result.

[server.rs L151](https://github.com/petabi/review-protocol/blob/main/src/server.rs#L151)

However, in request.rs, it expects the data to be wrapped in a Result.

[request.rs L198](https://github.com/petabi/review-protocol/blob/main/src/request.rs#L198)

I think this mismatch is causing issue in sending trust domains from server modules to client modules.

**Comment by msk** [comment]
@sophie-cluml, thanks for pointing out this inconsistency. You were correct that the mismatch between the data formats in server.rs and request.rs was causing issues. I've created a PR (#40) that aligns the data format for trusted domains in request.rs with the format used in server.rs, which should fix the problem. Your analysis was super helpful in tracking down the bug!
