### ISSUE TITLE
Modify HandshakeError::IncompatibleProtocol() to include agent name or agent ip address

### ISSUE THREAD

**Issue by syncpark** [petabi/review-protocol#8]
When an error occurred during the handshake between agent and REview, there is no hint as to which agent the error occurred from.

I think it's needed to extend the enum member `HandshakeError::IncompatibleProtocol(String, String)` to include **app_name** or **agent ip address**.

**Comment by msk** [comment]
@syncpark, you're right that it would be helpful to include more information about which agent the error occurred from. However, I think we can already get the agent's IP address from the `Connection` instance that's passed to the `handshake` function. We can use [`Connection::remote_address`](https://docs.rs/quinn/latest/quinn/struct.Connection.html#method.remote_address) to get the IP address, so it might not be necessary to include it in the `HandshakeError` enum. What do you think?

**Comment by syncpark** [comment]
@msk 
Then the program that call the `handshake()` function can get the remote ip address and print it too!

Okay. I think that's enough. I'll close this issue.
